# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e153ba8c80b222ee1c1d3ef0813b111f75816ad629f01f6aed21a362a47936188de71413ce1a20a86456a8b120662140541f5a6ffa8eba414898a0ba1f669e7

test:
  secret_key_base: cffe4cbd0adfdb0b5436d9b1a605d8b501f1d54515914c7d6c013d457ac7b50e1011f15a1d13d6afca862d0d4f915ec84afee1f8858d4add88226fa6dee231d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
